export const Columns = [
  { key: "id", label: "id" },
  { key: "nombre", label: "Categoria" },
  { key: "icono", label: "icono" },
];
export const fields = [
  { name: "nombre", label: "Categoria", type: "text" },
  {
    name: "icono",
    label: "Seleccione Icono",
    type: "select",
    options: [
      { value: "🍇", label: "🍇" },
      { value: "🍔", label: "🍔" },
      { value: "🍉", label: "🍉" },
      { value: "🍈", label: "🍈" },
      { value: "🍊", label: "🍊" },
      { value: "🍋", label: "🍋" },
      { value: "🍌", label: "🍌" },
      { value: "🍍", label: "🍍" },
      { value: "🥭", label: "🥭" },
      { value: "🍎", label: "🍎" },
      { value: "🍏", label: "🍏" },
      { value: "🍐", label: "🍐" },
      { value: "🍑", label: "🍑" },
      { value: "🍒", label: "🍒" },
      { value: "🍓", label: "🍓" },
      { value: "🫐", label: "🫐" },
      { value: "🥝", label: "🥝" },
      { value: "🍅", label: "🍅" },
      { value: "🥥", label: "🥥" },
      { value: "🥑", label: "🥑" },
      { value: "🍞", label: "🍞" },
      { value: "🥐", label: "🥐" },
      { value: "🥖", label: "🥖" },
      { value: "🥨", label: "🥨" },
      { value: "🧀", label: "🧀" },
      { value: "🍗", label: "🍗" },
      { value: "🍖", label: "🍖" },
      { value: "🥩", label: "🥩" },
      { value: "🍟", label: "🍟" },
      { value: "🍕", label: "🍕" },
      { value: "🌭", label: "🌭" },
      { value: "🍳", label: "🍳" },
      { value: "🥘", label: "🥘" },
      { value: "🍝", label: "🍝" },
      { value: "🍜", label: "🍜" },
      { value: "🍲", label: "🍲" },
      { value: "🥗", label: "🥗" },
      { value: "🍣", label: "🍣" },
      { value: "🍤", label: "🍤" },
      { value: "🍚", label: "🍚" },
      { value: "🍛", label: "🍛" },
      { value: "🍰", label: "🍰" },
      { value: "🎂", label: "🎂" },
      { value: "🧁", label: "🧁" },
      { value: "🍩", label: "🍩" },
      { value: "🍪", label: "🍪" },
      { value: "🍫", label: "🍫" },
      { value: "🍬", label: "🍬" },
      { value: "🍯", label: "🍯" },
      { value: "☕", label: "☕" },
      { value: "🍵", label: "🍵" },
      { value: "🍺", label: "🍺" },
      { value: "🍻", label: "🍻" },
      { value: "🥂", label: "🥂" },
      { value: "🍷", label: "🍷" },
      { value: "🍹", label: "🍹" },
      { value: "🍸", label: "🍸" },
    ],
  },
  { name: "id", label: "ID", type: "number", disable: true },
];
