export const Columns = [
  { key: "idnegocio", label: "id" },
  { key: "logo_negocio", label: "logo" },
  { key: "Negocio", label: "Negocio" },
  { key: "Categoria", label: "Categoria" },
  { key: "usuario", label: "Usuario" },
  { key: "direccion", label: "direccion" },
  { key: "telefono", label: "telefono" },
  { key: "email", label: "email" },
  { key: "created_at", label: "created_at" },
];
export const fields = [
  { 
    name: "usuario_id", 
    label: "usuarios",
    type: "dinamiselect",
    url:'/api/usuarios/controller.php',
    value:'id', 
    text:'nombre', 
  },
  { name: "usuario_id", label: "usuario_id", type: "number" },
  { name: "categoria_id", label: "categoria_id", type: "text" },
  { name: "nombre", label: "nombre", type: "text" },
  { name: "direccion", label: "direccion", type: "text" },
  { name: "telefono", label: "telefono", type: "number" },
  { name: "email", label: "email", type: "email" },
  { name: "logo", label: "img", type: "file" },
  { name: "Horario_inicial", label: "Horario_inicial", type: "time" },
  { name: "Horario_final", label: "Horario_final", type: "time" },
];
